// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrOe9hfwykSEwXNfI_SAVQQFFxSWGgQe8',
    appId: '1:1096211539073:web:31ae589560b1f4de64d980',
    messagingSenderId: '1096211539073',
    projectId: 'pencatatantugas',
    authDomain: 'pencatatantugas.firebaseapp.com',
    storageBucket: 'pencatatantugas.appspot.com',
    measurementId: 'G-WSH9WLF4ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjMRQ0eXgqUXgV7NL1dhhaXNRBHwV8qRs',
    appId: '1:1096211539073:android:ba788097b27df59d64d980',
    messagingSenderId: '1096211539073',
    projectId: 'pencatatantugas',
    storageBucket: 'pencatatantugas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtWfjmZwJbhnNl27QNRVcVCR9l44mNxjY',
    appId: '1:1096211539073:ios:54efbf8710a4ca3764d980',
    messagingSenderId: '1096211539073',
    projectId: 'pencatatantugas',
    storageBucket: 'pencatatantugas.appspot.com',
    iosBundleId: 'com.example.percobaan2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtWfjmZwJbhnNl27QNRVcVCR9l44mNxjY',
    appId: '1:1096211539073:ios:fe6f6dae7978971564d980',
    messagingSenderId: '1096211539073',
    projectId: 'pencatatantugas',
    storageBucket: 'pencatatantugas.appspot.com',
    iosBundleId: 'com.example.percobaan2.RunnerTests',
  );
}
